on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  echoss:
    permissions:
      # write permission is required to create a github release
      # contents: write
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - name : Print Title of PR
        run: |
          export count=$(echo "${{ github.event.pull_request.title }}" | grep -Eic "^\[?(dren|drop|dcor)-[0-9]+\]?")
          echo "dren occured count $count"
          if [ $count -eq 0 ]; then 
            export matchString=$(echo "${{ github.event.pull_request.body }}" | grep -Eoi -m 1 "\[?(dren|drop|dcor)-[0-9]+\]?" | head -1)
            echo "matching - $matchString"
          else 
            echo "match found" 
          fi  
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }} \
            -d '{"title":"'$matchString' ${{ github.event.pull_request.title }}"}'
