on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  echoss:
    runs-on: ubuntu-20.04
    steps:
      - name : Print Title of PR
        run: |
          export count=$(echo "${{ github.event.pull_request.title }}" | grep -Eic "^\[?(dren|drop|dcor)-[0-9]+\]?")
          echo "dren occured count $count"
          if [ $count -eq 0 ]; then 
            export matchString=$(echo "${{ github.event.pull_request.body }}" | grep -Eoi "^\[?(dren|drop|dcor)-[0-9]+\]?")
            echo "matching - $matchString"
          else 
            echo "match found" 
          fi
