on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  echoss:
    runs-on: ubuntu-20.04
    steps:
      - name : Print Title of PR
        run: |
          echo "The Title of your PR is ${{ github.event.pull_request.title }}"
          export count=$(echo "${{ github.event.pull_request.title }}" | grep -ci dren)
          echo "dren occured count $count"