on:
  pull_request:
    types: [opened]

jobs:
  update-title:
    permissions:
      pull-requests: write
    runs-on: ubuntu-20.04
    steps:
      - name : Read Title of PR
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          TITLE: ${{ github.event.pull_request.title }}
          BODY: ${{ github.event.pull_request.body }}
        run: |
          export count=$(echo $TITLE | grep -Eic "^\[?(dren|drop|dcor)-[0-9]+\]?")
          if [ $count -eq 0 ]; then 
            export ticketNumber=$(echo $BODY | grep -Eoi -m 1 "\[?(dren|drop|dcor)-[0-9]+\]?" | head -1)
            if [ -n $ticketNumber ]; then
              curl -L \
                -X PATCH \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/$REPO/pulls/$PR_NUMBER\
                -d '{"title":"'$ticketNumber' ${{ github.event.pull_request.title }}"}'
            else
              curl \
                -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token $TOKEN" \
                https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
                -d '{"body":":warning: Please add a ticket number to the PR"}'
            fi