name: get changed files

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check tests"
  check-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            test:
              - test/**
      - name: Run step if test file(s) change
        if: steps.changed-files-yaml.outputs.test_any_changed == 'true'  
        run: |
          echo "One or more test file(s) has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.test_all_changed_files }}"

