name: get changed files

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "check tests"
  check-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: get diff count
        id: diffCount
        run: |
          export COUNT=$(git diff --name-only -r HEAD^1 HEAD | grep -ic 'test*.kt' $1)
          if [ $COUNT -eq 0 ]; then
            echo "NO tests added/ modified"
          fi
          echo $COUNT
          echo "COUNT_DIFF=$(echo $COUNT)" >> $GITHUB_ENV

      - name: add comment to PR
        uses: mshick/add-pr-comment@v2
        if: env.COUNT_DIFF == 0
        with:
          message: |
            :warning: No Test files updated or added. Please add tests.
             files changed - ${{ env.COUNT_DIFF }}
              If you need to add a new ticket https://jira.grubhub.com/secure/Dashboard.jspa

      - name: use ENV VAR
        run: echo $COUNT_DIFF

