name: Publish Release
  
on:
  workflow_dispatch:

env:
  RELEASE_ID_LOCAL: ${{ vars.RELEASE_ID }}

jobs:
  build:
    name: Publisher
    runs-on: ubuntu-latest
    steps:
      - name: Get latest version
        id: latestVersion
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}

      - name: set outputs
        run: |
          echo "Latest rlease version ID is ${{ steps.latestVersion.outputs.id }}"
          echo "Latest rlease version TAG is ${{ steps.latestVersion.outputs.release }}"
          echo "Latest rlease version Body is ${{ steps.latestVersion.outputs.description }}"

