name: Publish Release
  
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    permissions:
      contents: write
    name: Publisher
    runs-on: ubuntu-latest
    steps:
      - name: drafter
        id: drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish:
            main

#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN:
#            ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: ${{steps.drafter.outputs.body}}
#          draft: false
#          prerelease: false

      - name: Edit Release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ steps.drafter.outputs.id }}
          name: Release ${{ github.ref }}
          draft: false
