name: Publish Release
  
on:
  workflow_dispatch:

env:
  RELEASE_ID_LOCAL: ${{ vars.RELEASE_ID }}

jobs:
  build:
    name: Publisher
    runs-on: ubuntu-latest
    steps:
      - name: Get latest version
        id: latestVersion
        uses: thebritican/fetch-latest-release@v1
        with:
          github_token: ${{ github.token }}

      - name: set outputs
        run: |
          echo "Latest rlease version ID is ${{ steps.latestVersion.outputs.id }}"
          echo "Latest rlease version TAG is ${{ steps.latestVersion.outputs.tag_name }}"
          echo "Latest rlease version Body is ${{ steps.latestVersion.outputs.body }}"
          echo "is it draft: ${{ steps.latestVersion.outputs.draft }}"

