name: Publish Release
  
on:
  workflow_dispatch:

env:
  temp_var: "body of the release"

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      RELEASE_ID: ${{ steps.drafter.outputs.id }}
      RELEASE_BODY: ${{ steps.drafter.outputs.body }}
    steps:
      - name: drafter
        id: drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main

  publish:
    name: Publisher
    runs-on: ubuntu-latest
    needs: update_release_draft
    steps:
      - env:
        ID: ${{needs.update_release_draft.outputs.RELEASE_ID}}
        BODY: ${{needs.update_release_draft.outputs.RELEASE_BODY}}

      - name: Checkout
        uses: actions/checkout@v3

      - name: GH Release
        uses: actions/create-release@v1
        id: latestVersion
        env:
          GITHUB_TOKEN:
            ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ID
          release_name: Release ID
          body: echo "$BODY"
          draft: false
          prerelease: false

