name: Publish Release
  
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    permissions:
      contents: write
    name: Publisher
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Notes
        id: drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main

      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN:
            ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.drafter.outputs.id}}
          release_name: Release ${{steps.drafter.outputs.id}}
          body: ${{steps.drafter.outputs.body}}
          draft: false
          prerelease: false

      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
