name: Publish Release
  
on:
  workflow_dispatch:

env:
  temp_var: "body of the release"

jobs:
  build:
    name: Publisher
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: cat ReleaseNotes.txt > temp_var

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        id: latestVersion
        with:
          files: ReleaseNotes.txt
          body: temp_var

      - name: set outputs
        run: |
          echo "Latest rlease version ID is ${{ steps.latestVersion.outputs.id }}"
          echo "Latest rlease version TAG is ${{ steps.latestVersion.outputs.tag_name }}"
          echo "Latest rlease version Body is ${{ steps.latestVersion.outputs.body }}"
          echo "is it draft: ${{ steps.latestVersion.outputs.draft }}"

