name: Publish Release
  
on:
  workflow_dispatch:

jobs:
  prepare-notes:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      RELEASE_ID: ${{ steps.drafter.outputs.id }}
      RELEASE_BODY: ${{ steps.drafter.outputs.body }}
    steps:
      - name: drafter
        id: drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main

  publish:
    permissions:
      contents: write
    name: Publisher
    runs-on: ubuntu-latest
    needs: prepare-notes
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GH Release
        uses: actions/create-release@v1
        id: latestVersion
        env:
          GITHUB_TOKEN:
            ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{needs.prepare-notes.outputs.RELEASE_ID}}
          release_name: Release ${{needs.prepare-notes.outputs.RELEASE_ID}}
          body: ${{needs.prepare-notes.outputs.RELEASE_BODY}}
          draft: false
          prerelease: false

      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
