name: Publish Release
  
on:
  workflow_dispatch:

env:
  RELEASE_ID_LOCAL: ${{ vars.RELEASE_ID }}

jobs:
  build:
    name: Publisher
    runs-on: ubuntu-latest
    steps:
      - run: echo $RELEASE_ID_LOCAL
